### ISSUE TITLE
web login doesn't work

### ISSUE THREAD

**Issue by heidricha** [ome/omero-grid-docker#3]
after built the instances, I can connect using CLI, but not on web.

I run a slightly modified master image (added local proxy configuration and a few tools, like vim and sudo) and untouched web image (doesn't work with the same modifications I applied to master)

```
docker run -d --name postgres -e POSTGRES_PASSWORD=postgres postgres

docker run -d --name omero-master --link postgres:db -e DBUSER=postgres -e DBPASS=postgres -e DBNAME=postgres -p 4063:4063 -p 4064:4064 openmicroscopy/omero-grid master

docker run -d --name omero-web --link omero-master:master -p 8088:8080 openmicroscopy/omero-grid-web

```
Changed the root experimenter's password, can connect on using "omero login"
Web starts without errors, there's communication between web and master when I try to login on the web interface, but login isn't successful:
"Error: Server is not responding, please contact administrator."

Where to check for errors?

**Comment by joshmoore** [comment]
Hi @heidricha. What is your exact build command? Are your changes pushed somewhere? What does `docker logs` show for the failing container?

Likely what's happened is that with the release this week, http://downloads.openmicroscopy.org/omero/latest now points at 5.3 rather than 5.2 and there is a breaking change.

Are you looking to use 5.2 or 5.3 or it doesn't matter?

**Comment by dpwrussell** [comment]
Edit: Ignore this, I thought this was about https://github.com/ome/ome-docker

**Comment by heidricha** [comment]
not pushed, just local mods:

```
heidricha@WS1429-T5810-L:~/Work/omero-grid-docker$ git diff 
diff --git a/omero-grid-web/Dockerfile b/omero-grid-web/Dockerfile
index ee5d65d..94e3db6 100644
--- a/omero-grid-web/Dockerfile
+++ b/omero-grid-web/Dockerfile
@@ -1,10 +1,17 @@
 FROM centos:centos7
 MAINTAINER ome-devel@lists.openmicroscopy.org.uk
 
+ENV http_proxy=http://git:3128 \
+    https_proxy=http://git:3128 \
+    HTTP_PROXY=http://git:3128 \
+    HTTPS_PROXY=http://git:3128 \
+    no_proxy="localhost,.eli-alps.local" \
+    NO_PROXY="localhost,.eli-alps.local"
+
 # TODO: Use separate Nginx container
 
 RUN yum -y install epel-release && \
-    yum -y install ansible
+    yum -y install ansible vim sudo
 
 RUN mkdir /opt/infrastructure
 ADD omero-grid-web-deps.yml requirements.yml /opt/infrastructure/
@@ -28,6 +35,8 @@ RUN useradd omero && \
     #ln -sf /dev/stdout /var/log/nginx/access.log && \
     #ln -sf /dev/stderr /var/log/nginx/error.log && \
 
+RUN echo "omero        ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/omero
+
 ARG OMERO_VERSION=latest
 ARG CI_SERVER
 ARG OMEGO_ARGS
diff --git a/omero-grid/Dockerfile b/omero-grid/Dockerfile
index 7fce5cf..24a2060 100644
--- a/omero-grid/Dockerfile
+++ b/omero-grid/Dockerfile
@@ -1,9 +1,14 @@
 FROM centos:centos7
 MAINTAINER ome-devel@lists.openmicroscopy.org.uk
 
+ENV http_proxy=http://git:3128 \
+    https_proxy=http://git:3128 \
+    HTTP_PROXY=http://git:3128 \
+    HTTPS_PROXY=http://git:3128 \
+    no_proxy="localhost,.eli-alps.local" \
+    NO_PROXY="localhost,.eli-alps.local"
 
-RUN yum -y install epel-release && \
-    yum -y install ansible
+RUN yum -y install epel-release && yum -y install ansible sudo vim
 
 RUN mkdir /opt/infrastructure
 ADD omero-grid-deps.yml requirements.yml /opt/infrastructure/
@@ -18,6 +23,8 @@ RUN useradd omero && \
     mkdir /OMERO && \
     chown omero /OMERO
 
+RUN echo "omero        ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/omero
+
 ARG OMERO_VERSION=latest
 ARG CI_SERVER
 ARG OMEGO_ARGS
```
build ends well, master image works as expected (and as it does without the mods)

staring web container end with the log below:

```
Creating /etc/nginx/conf.d/omero-web.conf
Starting OMERO.web
Traceback (most recent call last):
  File "manage.py", line 56, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named pipeline
```

**Comment by heidricha** [comment]
Great! with that patch I can build a web image, and it really works now!

Thanks a lot!
